"use client";
import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'hero.greeting': "Hey, I'm Samir",
    'hero.title': "Full Stack",
    'hero.subtitle': "Mobile & Web developer",
    'hero.description': "With expertise in cutting-edge technologies such as",
    'hero.description2': "... I deliver mobile and web solutions that are both innovative and robust.",
    'hero.andMore': "...and more",
    'hero.downloadCV': "[ Download my CV ]",
    'nav.home': "Home",
    'nav.about': "About me",
    'nav.services': "Services",
    'nav.resume': "Resume",
    'nav.portfolio': "Projects",
    'nav.blog': "Blog",
    'nav.contact': "Contact",
    'offcanvas.getInTouch': "Get in touch",
    'offcanvas.description': "I'm always excited to take on new projects and collaborate with innovative minds.",
    'offcanvas.phoneNumber': "Phone Number",
    'offcanvas.email': "Email",
    'offcanvas.social': "Social",
    'services.cooperation': "Cooperation",
    'services.title': "Designing solutions",
    'services.subtitle': "customized to meet your requirements",
    'services.mobileWeb.title': "Mobile & Web Development",
    'services.mobileWeb.description': "Creating cross-platform mobile apps with Flutter and responsive web applications using React, HTML, CSS, and Tailwind CSS.",
    'services.backend.title': "Backend & Database Solutions",
    'services.backend.description': "Building robust backend systems with Supabase, NodeJS, and Django. Managing databases with PostgreSQL, SQLite, and MySQL.",
    'services.api.title': "API Development & Integration",
    'services.api.description': "Creating and integrating RESTful APIs to enable seamless communication between systems and third-party services.",
    'services.devops.title': "DevOps & Deployment",
    'services.devops.description': "Managing deployments and infrastructure using Git, Docker, Hetzner, and automation tools like N8N.",
    'services.fullstack.title': "Full-Stack Solutions",
    'services.fullstack.description': "End-to-end development solutions combining frontend and backend technologies following Agile Methodologies for efficient project delivery.",
    'services.automation.title': "Automation & AI Integration",
    'services.automation.description': "Streamlining business processes with automation tools and integrating AI solutions to improve efficiency, enhance user experience, and provide intelligent automation capabilities.",
    'services.footer.text': "Excited to take on new projects and collaborate. Let's chat about your ideas.",
    'services.footer.link': "Reach out!",
    'experience.title': "Experience",
    'experience.years': "+3 years of passion",
    'experience.subtitle': "for development and innovation",
    'experience.position': "Full Stack Developer",
    'experience.description1': "Developed scalable mobile and web applications using Flutter and React, improving user experience and performance.",
    'experience.description2': "Implemented backend solutions with Supabase and NodeJS for robust data management.",
    'experience.description3': "Collaborated with cross-functional teams to deliver innovative solutions using modern technologies.",
    'experience.present': "present",
    'projects.title': "Projects",
    'projects.subtitle': "My Recent Works",
    'projects.projectInfo': "Project Info",
    'projects.client': "Client",
    'projects.completionTime': "Completion Time",
    'projects.technologies': "Technologies",
    'projects.viewProject': "View Project",
    'projects.viewPlayStore': "View on Play Store",
    'projects.viewGitHub': "View on GitHub",
    'projects.privateProject': "Private Project",
    'projects.months': "Months",
    'projects.month': "Month",
    'projects.week': "Week",
    'projects.repsys.title': "Complete ERP for Technical Assistance",
    'projects.repsys.description': "Implementation of entire front-end system, backend, payment gateway integration and landing page",
    'projects.studioflow.title': "App for Music Studio Management",
    'projects.studioflow.description': "Complete application for music studio management with scheduling, financial control and client management",
    'projects.poupix.title': "Expense Management App",
    'projects.poupix.description': "Case study for implementing the architecture suggested by Flutter's official documentation",
    'projects.assets.title': "Maintenance Asset Management System",
    'projects.assets.description': "Complete platform for maintenance asset control and management with analytical dashboard and reports",
    'projects.daikin.title': "Rewards Program App",
    'projects.daikin.description': "Backend integration for installer rewards and loyalty system",
    'skills.title': "Skills",
    'skills.subtitle': "My Skills",
    'skills.frontend': "Front-End:",
    'skills.backend': "Back-End:",
    'skills.databases': "Databases:",
    'skills.tools': "Tools & Platforms:",
    'skills.others': "Others:",
    'contact.title': "Let's connect",
    'contact.name': "Your name",
    'contact.phone': "Phone",
    'contact.email': "Email",
    'contact.subject': "Subject",
    'contact.message': "Message",
    'contact.sendMessage': "Send Message",
    'contact.phoneNumber': "Phone Number",
    'contact.linkedin': "Linkedin",
    'contact.sending': "Sending...",
    'contact.successMessage': "Message sent successfully! I'll get in touch soon.",
    'contact.errorMessage': "Error sending message. Please try again or contact me via WhatsApp.",
    'education.title': "Education",
    'education.certifications': "Certifications",
    'education.uninter.course': "Systems Analysis and Development | Brazil",
    'education.ufrn.course': "Bachelor's Degree in Chemistry | Brazil",
    'education.ifrn.course': "Technical in Electrical Engineering | Brazil",
    'education.flutter.title': "Advanced Flutter Development",
    'education.flutter.description': "Advanced architectures, state management and performance optimization following official documentation",
    'education.meta.title': "Meta Android Developer Specialization",
    'education.meta.description': "Kotlin programming, interface creation with Android Studio and Jetpack Compose",
    'education.dio.title': "DIO Backend Bootcamp with Kotlin",
    'education.dio.description': "Backend programming with Kotlin, REST API creation, test development and documentation."
  },
  pt: {
    'hero.greeting': "Olá, eu sou Samir",
    'hero.title': "Full Stack",
    'hero.subtitle': "Dev Mobile & Web",
    'hero.description': "Com expertise em tecnologias de ponta como",
    'hero.description2': "... Eu entrego soluções mobile e web inovadoras e robustas.",
    'hero.andMore': "...e mais",
    'hero.downloadCV': "[ Baixar meu CV ]",
    'nav.home': "Início",
    'nav.about': "Sobre mim",
    'nav.services': "Serviços",
    'nav.resume': "Currículo",
    'nav.portfolio': "Projetos",
    'nav.blog': "Blog",
    'nav.contact': "Contato",
    'offcanvas.getInTouch': "Entre em contato",
    'offcanvas.description': "Estou sempre animado para assumir novos projetos e colaborar com mentes inovadoras.",
    'offcanvas.phoneNumber': "Número de Telefone",
    'offcanvas.email': "Email",
    'offcanvas.social': "Social",
    'services.cooperation': "Cooperação",
    'services.title': "Projetando soluções",
    'services.subtitle': "personalizadas para atender suas necessidades",
    'services.mobileWeb.title': "Desenvolvimento Mobile & Web",
    'services.mobileWeb.description': "Criando aplicativos móveis multiplataforma com Flutter e aplicações web responsivas usando React, HTML, CSS e Tailwind CSS.",
    'services.backend.title': "Soluções Backend & Banco de Dados",
    'services.backend.description': "Construindo sistemas backend robustos com Supabase, NodeJS e Django. Gerenciando bancos de dados com PostgreSQL, SQLite e MySQL.",
    'services.api.title': "Desenvolvimento & Integração de APIs",
    'services.api.description': "Criando e integrando APIs RESTful para permitir comunicação perfeita entre sistemas e serviços de terceiros.",
    'services.devops.title': "DevOps & Deploy",
    'services.devops.description': "Gerenciando deploys e infraestrutura usando Git, Docker, Hetzner e ferramentas de automação como N8N.",
    'services.fullstack.title': "Soluções Full-Stack",
    'services.fullstack.description': "Soluções de desenvolvimento completas combinando tecnologias frontend e backend seguindo Metodologias Ágeis para entrega eficiente de projetos.",
    'services.automation.title': "Automação & Integração de IA",
    'services.automation.description': "Otimizando processos de negócio com ferramentas de automação e integrando soluções de IA para melhorar eficiência, experiência do usuário e fornecer capacidades de automação inteligente.",
    'services.footer.text': "Animado para assumir novos projetos e colaborar. Vamos conversar sobre suas ideias.",
    'services.footer.link': "Entre em contato!",
    'experience.title': "Experiência",
    'experience.years': "+3 anos de paixão",
    'experience.subtitle': "por desenvolvimento e inovação",
    'experience.position': "Desenvolvedor Full Stack",
    'experience.description1': "Desenvolvi aplicações móveis e web escaláveis usando Flutter e React, melhorando a experiência do usuário e performance.",
    'experience.description2': "Implementei soluções backend com Supabase e NodeJS para gerenciamento robusto de dados.",
    'experience.description3': "Colaborei com equipes multifuncionais para entregar soluções inovadoras usando tecnologias modernas.",
    'experience.present': "presente",
    'projects.title': "Projetos",
    'projects.subtitle': "Meus Trabalhos Recentes",
    'projects.projectInfo': "Info do Projeto",
    'projects.client': "Cliente",
    'projects.completionTime': "Tempo de Conclusão",
    'projects.technologies': "Tecnologias",
    'projects.viewProject': "Ver Projeto",
    'projects.viewPlayStore': "Ver na Play Store",
    'projects.viewGitHub': "Ver no GitHub",
    'projects.privateProject': "Projeto Privado",
    'projects.months': "Meses",
    'projects.month': "Mês",
    'projects.week': "Semana",
    'projects.repsys.title': "ERP Completo para Assistências Técnicas",
    'projects.repsys.description': "Implementação de todo sistema front, backend, integração com gateway de pagamento e landing page",
    'projects.studioflow.title': "App para Gestão de Estúdios Musicais",
    'projects.studioflow.description': "Aplicativo completo para gerenciamento de estúdios musicais com agendamento, controle financeiro e gestão de clientes",
    'projects.poupix.title': "App para Gestão de Despesas",
    'projects.poupix.description': "Case de estudo para implementação da arquitetura sugerida pela documentação oficial do Flutter",
    'projects.assets.title': "Sistema de Gestão de Ativos de Manutenção",
    'projects.assets.description': "Plataforma completa para controle e gestão de ativos de manutenção com dashboard analítico e relatórios",
    'projects.daikin.title': "App para Programa de Recompensas",
    'projects.daikin.description': "Integração com backend para sistema de recompensas e fidelidade de instaladores",
    'skills.title': "Habilidades",
    'skills.subtitle': "Minhas Habilidades",
    'skills.frontend': "Front-End:",
    'skills.backend': "Back-End:",
    'skills.databases': "Bancos de Dados:",
    'skills.tools': "Ferramentas e Plataformas:",
    'skills.others': "Outros:",
    'contact.title': "Vamos nos conectar",
    'contact.name': "Seu nome",
    'contact.phone': "Telefone",
    'contact.email': "Email",
    'contact.subject': "Assunto",
    'contact.message': "Mensagem",
    'contact.sendMessage': "Enviar Mensagem",
    'contact.phoneNumber': "Número de Telefone",
    'contact.linkedin': "Linkedin",
    'contact.sending': "Enviando...",
    'contact.successMessage': "Mensagem enviada com sucesso! Entrarei em contato em breve.",
    'contact.errorMessage': "Erro ao enviar mensagem. Tente novamente ou entre em contato pelo WhatsApp.",
    'education.title': "Educação",
    'education.certifications': "Certificações",
    'education.uninter.course': "Análise e Desenvolvimento de Sistemas | Brasil",
    'education.ufrn.course': "Licenciatura em Química | Brasil",
    'education.ifrn.course': "Técnico em Eletrotécnica | Brasil",
    'education.flutter.title': "Desenvolvimento Flutter Avançado",
    'education.flutter.description': "Arquiteturas avançadas, gerenciamento de estado e otimização de performance seguindo a documentação oficial",
    'education.meta.title': "Meta Android Developer Specialization",
    'education.meta.description': "Programação em Kotlin, criação de interfaces com Android Studio e Jetpack Compose",
    'education.dio.title': "Bootcamp DIO Backend com Kotlin",
    'education.dio.description': "Programação backend com Kotlin, criação de APIs REST, elaboração de testes e documentação."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}